[project]
name = "evaluation"
version = "0.1.0"
description = "Evaluate and compare models"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "jinja2>=3.1.6",
    "pydantic>=2.11.7",
    "tqdm>=4.67.1",
    "python-dotenv",
    "openai",
]
